package dk.mmj.eevhe.crypto.keygeneration;

import java.math.BigInteger;

/**
 * Extended Key Generation Parameters for use in Gennaro Distributed Key Generation
 */
public interface ExtendedKeyGenerationParameters extends KeyGenerationParameters {
    /**
     * returns group element <code>e</code> generated by generator <code>g</code> for the group
     *
     * @return {@link BigInteger} representing e
     */
    BigInteger getGroupElement();
}
