package dk.mmj.eevhe.protocols.interfaces;

import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Interface for an arbitrary Distributed Key Generation
 */
public interface DKG<T> {

    /**
     * Generates and returns the steps which makes up the protocol
     *
     * @return list of steps to be executed
     */
    List<Step> getSteps();

    /**
     * Outputs keys of type T
     *
     * @return output generated by the protocol
     */
    T output();

    class Step {
        private final Runnable executor;
        private final long delay;
        private final TimeUnit timeUnit;

        public Step(Runnable executor, long delay, TimeUnit timeUnit) {
            this.executor = executor;
            this.delay = delay;
            this.timeUnit = timeUnit;
        }

        public Runnable getExecutable() {
            return executor;
        }

        public long getDelay() {
            return delay;
        }

        public TimeUnit getTimeUnit() {
            return timeUnit;
        }
    }
}
